export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { CryptoProvider } from './context/CryptoContext';
import { SearchProvider } from './context/SearchContext';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CryptoProvider>
          <SearchProvider>
            {children}
          </SearchProvider>
        </CryptoProvider>
      </body>
    </html>
  )
}
